ADD Deployment Guide
kartikayasijaa/talk-trove pull request #160
Opened 2024-10-24 11:47 UTC by alo7lika

- Fixes #151

## 📋 Description
Added a comprehensive Deployment Guide for the Full Stack Chatting App to assist users in deploying the application on their servers.

## 🔨 Changes Made

- Created a new section in the README for the Deployment Guide.
- Provided detailed steps for deploying both frontend and backend components.
- Included configurations for web servers like NGINX for handling routing and SSL setup.

## 🔨 Screen Shots OR Short videos of working
![Screenshot 2024-10-24 171245](https://github.com/user-attachments/assets/a0dafb54-3049-44c0-9eae-73104465d2a0)

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] Read Contributing.md

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [x] Documentation update 📚

## 🤝 Related Issues
N/A

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to Talk-Trove! We look forward to reviewing your PR and getting it merged!*

2024-10-24 11:55 UTC, Sibam-Paul requested changes

2024-10-24 11:55 UTC, Sibam-Paul commented on README.md
> +  PORT=your_preferred_port
Mention there is a env.sample in the file to rename it to .env just tell all the above are there in .env.sample file and mention the above and just rename it as instructions in the readme

2024-10-24 11:57 UTC, Sibam-Paul requested changes

2024-10-24 11:57 UTC, Sibam-Paul commented on README.md
> +- Use a web server like **NGINX** or **Apache** to serve the frontend.
Also add if u don't have mongodb write the setup of docker

2024-10-24 11:58 UTC, alo7lika commented
@kartikayasijaa  and @Sibam-Paul  the task has been completed.
Kindly add the labels GSSOC Ext 24 and HACKTOBERFEST

2024-10-24 12:07 UTC, alo7lika commented
> @kartikayasijaa and @Sibam-Paul the task has been completed. Kindly add the labels GSSOC Ext 24 and HACKTOBERFEST

Made the changes @Sibam-Paul

2024-10-25 16:24 UTC, alo7lika commented
> > @kartikayasijaa and @Sibam-Paul the task has been completed. Kindly add the labels GSSOC Ext 24 and HACKTOBERFEST
> 
> Made the changes @Sibam-Paul

@Sibam-Paul

2024-10-25 16:57 UTC, kartikayasijaa commented
@alo7lika Can we connect over discord for this PR?

2024-10-25 18:57 UTC, alo7lika commented
> @alo7lika Can we connect over discord for this PR?

Do I need to make any more changes?

2024-10-25 19:02 UTC, kartikayasijaa commented
Yes, we can't add this in readme. This information will not make any sense there.
@alo7lika

2024-11-10 11:47 UTC, closed without merging