methods are made for emai template and email confirigation using gmail smtp server
kartikayasijaa/talk-trove pull request #22
Opened 2024-10-05 17:13 UTC by praveenarjun

## 📋 Description

# I used Mail nodemailer because normal sending and verifying mail is costly. In my code, the admin's Gmail has an option to send mail to anyone. I created the email templates and email generation.

## 🔨 Changes Made

 
- Created a folder in backend name mailtrap
 inside it I create email.js,emailTemplate,email trapconfig.js 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

export const MailtrapClient = nodemailer.createTransport({
    service: 'gmail', // or any other service like 'yahoo', 'outlook', etc.
    auth: {
        user: '', // your email address Generally to send mail it will be costly so u can add you gmail in gmail setting u can accept to send mail to any one and generate password
        pass: ' '    // your email password
    }
    need to add the name and password generated by smtp server of google 
     can refer this  ## https://www.youtube.com/watch?v=kTcmbZqNiGw link to generate 
     
     I only run my email verification because there is a issue in my docker desktop so Admin pls add Your mail and password in the place you can verify it
     
     Even I used Postman for api testing in the next pull request i will add the controller and router for this mail verification

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots
![Screenshot 2024-10-05 at 10 40 53 PM](https://github.com/user-attachments/assets/ee15ab50-951a-4e6d-8a7a-e4636f71cce9)

 (if app
![Screenshot_20241005_222449_Gmail](https://github.com/user-attachments/assets/54d20ff8-865e-4bf8-adbb-c20dded65b06)
licable)

---

## Reminder:

I created My own new Branch named as Email verification and email But I dont know how to pull request to your test branch here it is showing only main 
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to VigneshDevHub! We look forward to reviewing your PR and getting it merged!*

2024-10-06 13:59 UTC, Sibam-Paul requested changes

2024-10-06 13:59 UTC, Sibam-Paul commented on backend/routes/userRoutes.js
> +router.post("/forgot-password", forgotPassword);
Hey I think for forget password the issue is there #2 put for mail confirmation hmm.. wait let me see

2024-10-06 13:59 UTC, Sibam-Paul commented on backend/routes/userRoutes.js
> +router.post("/forgot-password", forgotPassword);
@praveenarjun Please add a short video of the changes u made and along with it's woking,  seeing fine with the code but with forget password having second thoughts

2024-10-06 14:01 UTC, Sibam-Paul commented
@praveenarjun U added methods in backend but I think for forget password #2 is working on it 
may cause contrast

2024-10-06 14:03 UTC, praveenarjun commented
It may occur due to there need to generate a bearer token so that the token is generated and need to add a token time of expire by that only you can access the verification of email

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Sibam Paul ***@***.***>
Sent: Sunday, October 6, 2024 7:31:45 PM
To: kartikayasijaa/talk-trove ***@***.***>
Cc: CHALLA SREE PRAVEEN ***@***.***>; Mention ***@***.***>
Subject: Re: [kartikayasijaa/talk-trove] methods are made for emai template and email confirigation using gmail smtp server (PR #22)


@praveenarjun<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fpraveenarjun&data=eJxEy8FuhCAQANCvgUMTFAasmpSmvfgfI45dVhcMDJv07_e455cXvAZyZoNRrdYa5Sa9KzS0q08LNE7zjDSvcvMf8uG_DiwcD_zHGu-IPeN5KC75Sf3VzrMH6APYeXCDGafh5y_yra1dyI9vWX3KHPcYkGNOVTj9Vlk8AYRKTZvRCKdXSomYO9paF5Ns_sZ8VWF_BSwClvcUsFwFn0QJy72lVwAAAP__ssRCvA%%> U added methods in backend but I think for forget password #2<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fkartikayasijaa%2Ftalk-trove%2Fissues%2F2&data=eJxUzsFuhCAQgOGnGQ5NWGHAqklp2gvvMeLYpbq4kaFJ375H0_OfP_lSMMjeLjjo2Tmr_WhWTZZX_eqQh3GaiKdZLeFFPcLbRqfkjX6p5m-iTmjftJzHD3fPtu8dYpfQTb3v7TD2H19Z7m2-pePxrmooh-Q1J5J8lAreXFWdgRFT5WbsYMGbmUthkRsv7ZaLauEu8qzgPgEjYLxOwPifBBgvFGDMtTaugBH_AgAA__-Jqkwi> is working on it
may cause contrast

—
Reply to this email directly, view it on GitHub<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fkartikayasijaa%2Ftalk-trove%2Fpull%2F22%23issuecomment-2395451785&data=eJxUzsFurSAQgOGnGRY3QWHAqyalaTe8B-LYQ1U4kaFJ377pynT950--6BSS1SuOcjFGSzupTQZNm_xvkMZpngPNi1jdP3G6lz1cnPbwHWr6DKHncOySr_JF_bMdR4_YRzTzYAc9TsPbR-JHW7pYzldRXS6cthQDp5IrWHVXcTlCjJWa0qMGqxbKmZg7WluXsmjuwfysYN4BPaC_T0D_lwTobxSg_2UBekRAk2ptFMt5UmZ5M38CAAD__1nwU1k%>, or unsubscribe<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7D4WAX2HSDM53642ESYXUTZ2E7ETAVCNFSM6AAAAABPNQFGDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGQ2TCNZYGU&data=eJxUjNFusjAYQJ-mXPwJAl-LSPKzjIlFp6AEBPWuYJ2dWAxtl-ztl12ZnduTc7rIBU68MwR2i7Fnk5l7sZnHL_YUAw9mYch42Frn6J91j_7f2KjFjX0zJT4ZczTrb7Yehy_uPEzfOwBOBzj0ie8FM__1Q-iraSfdcH-xVCQHLS6iY1oMUiHiPq01RhygU9y4XuAh4rZcSq71hJ_NREjLRFetHwrhGAFFQJ8lAvp3C9RIZVrVjaLlNjP6ioDGQUKa-ADLMsl8PCWwKI-HfXWCRbCo4nqe0zKbxr-87fKCpsm6Xq4gKbO6aFYHvMlqgrflptrm0KwLvMvrplnjar_MTkm6fa_TAqp5fjqm-58AAAD__0HIaRo%>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-06 14:18 UTC, Sibam-Paul commented
@praveenarjun just dm me on discord my username specter102 or dm me in any general channel of gssoc-ext I need to see it live. as code is fine for me

2024-10-06 14:20 UTC, praveenarjun commented
Ok I will but pls add a level in label pull request

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Sibam Paul ***@***.***>
Sent: Sunday, October 6, 2024 7:48:45 PM
To: kartikayasijaa/talk-trove ***@***.***>
Cc: CHALLA SREE PRAVEEN ***@***.***>; Mention ***@***.***>
Subject: Re: [kartikayasijaa/talk-trove] methods are made for emai template and email confirigation using gmail smtp server (PR #22)


@praveenarjun<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fpraveenarjun&data=eJxEy8FuhCAQANCvgUMTFAZW16Q07cX_GHHssrpgYNikf9-j55cXvAZyZoVRLdYa5e56U2hoU4MFGu_ThDQtcvUf8uU_dywcd_zDGp-IPeOxKy75Tf3ZjqMH6APY6eZu4zAM37-RH23pQn59yepT5rjFgBxzqsLpS2XxBBAqNW1GI5xeKCVi7mhtXUyy-QfzWYX9ETALmK8pYD4LvokSlmdL_wEAAP__tJ5CwA%%> just dm me on discord my username specter102 or dm me in any general channel of gssoc-ext I need to see it live. as code is fine for me

—
Reply to this email directly, view it on GitHub<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fkartikayasijaa%2Ftalk-trove%2Fpull%2F22%23issuecomment-2395457666&data=eJxUzsFuhCAQgOGnGQ5NUBhYXZPStBfeA3HsUhU2MjTp2zc9mZ7__MkXnUKyesFRzsZoae9qlUHTKgeDNN6nKdA0i8W9iMO9buHktIWfUNNXCD2HfZN8lm_qn23fe8Q-oplu9jYOw_D-mfjR5i6W401UlwunNcXAqeQKVl1VnI4QY6Wm9KjBqplyJuaOltalLJp7MD8rmA9AD-ivE9D_JwH6CwXo_1iAHhHQpFobxXIclFlezN8AAAD__1ywU2E%>, or unsubscribe<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7D4WASTXE2U65FARAC5YNDZ2FBELAVCNFSM6AAAAABPNQFGDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGQ2TONRWGY&data=eJxUjFFvqjAYQH8NPNwEga8FJLnc3CoWnQIiCOpbwTo7FQxtl-zfL3syO68n53SRAxy7ZwisFiHXwlPnYjGXXywfAQ-mYch42Jrn6I_5iP7e2KjEjX0xKT4YsxW73yw1Dp_cfur73QawO0Chh73A9_3_70JddTvphsc_U0b9oMRFdEyJoZcGdl7WHCMO0EmuHTdwDey0vO-5UhN-1hPRmzq6KvWUBiIGUAPoqzSA_t4C1b3UrexG0XKLaXU1gJIgxg0pq8MC9r5HyY7MvWMWn4DOFhtSzzNapj75YbbNCprE63q5grhM66JZHdAmrTHKy02VZ9CsC7TN6qZZo2q_TE9xkr_VSQFVnu2a5PgdAAD__0uzaS8%>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-06 16:01 UTC, Sibam-Paul commented
@kartikayasija @kartikayasijaa yewala PR . Mujhe sahi lag raha hai .

2024-10-06 19:41 UTC, kartikayasijaa commented
> @kartikayasija @kartikayasijaa yewala PR . Mujhe sahi lag raha hai .

Everything is working right?

2024-10-07 12:34 UTC, Sibam-Paul commented
@praveenarjun Where I need to add my email ?? can u show me live in discord

2024-10-07 13:30 UTC, praveenarjun commented
Yes but where is the discord link

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Sibam Paul ***@***.***>
Sent: Monday, October 7, 2024 6:05:03 PM
To: kartikayasijaa/talk-trove ***@***.***>
Cc: CHALLA SREE PRAVEEN ***@***.***>; Mention ***@***.***>
Subject: Re: [kartikayasijaa/talk-trove] methods are made for emai template and email confirigation using gmail smtp server (PR #22)


@praveenarjun<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fpraveenarjun&data=eJxEy81uhCAQAOCngUMTFAbjT1Ka9uJ7DDh2WV0wMGzSt-_R85cvOA00mA0m5a01apj1rtDQrkYLNM3LgrR4ubkP-XKfBxaOB_5hjU_EnvE8FJf8pv5q59kD9AHsMs56nGD8_o38aL4L-fUlq0uZ4x4DcsypikHfKosjgFCpaTMZMWhPKRFzR1vrYpLNPZivKuyPgFXAek8B61XwTZSwPFv6DwAA__-y00K8> Where I need to add my email ?? can u show me live in discord

—
Reply to this email directly, view it on GitHub<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fkartikayasijaa%2Ftalk-trove%2Fpull%2F22%23issuecomment-2396806726&data=eJxUzs1qhTAQQOGnGReFaDIRf6Ap7SbvMcaxN1WTi5kU-valK-n6cOALTiP3ZsVRLdYa1U96U2R4U4NFHqd5Jp6XZnUvzeled7ok7vRDJX4RdULHruTK39w963F0iF1AOw-THkYc3j-jPOrShny-NcWlLHGLgSTmVKDXd20ux4ihcNVmNNDrhVNikZbX2sbUVPcQeRawH4Ae0N8noP9PAvQ3CtD_sQA9IqCNpVQO-Tw5ibqZvwEAAP__Wg5TWQ%%>, or unsubscribe<https://linklock.titanhq.com/analyse?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA7D4WAXKWAQ7XYHJPW4BDM3Z2J5XPAVCNFSM6AAAAABPNQFGDKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJWHAYDMNZSGY&data=eJxUjEFvgjAYQH8NHJYg8LUDScayOlJRBCE4it4K1tmpYGi7ZP9-2cnsXV_e62MPBPaPEDodQr6D597J4b44OQECEc6jiIuos4_xk32LXy580vLCf7iSX5y7ml8vjp7Gb-HezfXqArg9oCiYe0EIwdun1GfTzfrx9mqreBi1PMmeazkOysLew9pTLAB6JYznh76FvU4Mg9B6Jo5mJgfbxGet78pCxAJqAX2UFtD_W6BmUKZT_SQ74XCjzxZQEiaYkTZjpArbfbouGV4kOTrA-rktSfNe0DoPyB-LsqjoMsmadAVJnTcVW7VokzcYbevNblsAyypUFg1jGdp9pPkhWW7XLCX7JC8O9XL_GwAA__9gTGl4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

“All dreams are within reach. All you have to do is keep moving towards them.” –  Viola Davis

_____________________________________________

Vineet Jain (Chancellor) Inspiration

“All dreams are within reach. All you have to do is keep moving towards them.” –  Viola Davis

_____________________________________________

Vineet Jain (Chancellor) Inspiration

2024-10-07 13:47 UTC, praveenarjun commented
![IMG-20241007-WA0004](https://github.com/user-attachments/assets/e5f6b7ec-2b67-400c-b84e-cceb3d30aff0)
Here need to add the your mail and sender there is no need because it fetch from data base

2024-10-08 17:28 UTC, merged