Added password strength validation on signup page
kartikayasijaa/talk-trove pull request #65
Opened 2024-10-09 17:22 UTC by jvkousthub

- Fixes #25 

## 📋 Description

Turns into different colours depending on the password strength

## 🔨 Changes Made

- The input changes to different color based on the password strength
- weak password returns red
- medium gives orange
- strong password gives green
- solves #25 

## 🔨 Screen Shots OR Short videos of working

![image](https://github.com/user-attachments/assets/7faefefd-2e82-45a8-9ee6-2162d9da8f77)
![image](https://github.com/user-attachments/assets/f748f34f-ce47-4406-a841-01b35244e776)
![image](https://github.com/user-attachments/assets/f8ad5159-d579-4c22-bc03-0745e039d19b)

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] Read Contributing.md

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

## Reminder:
Please ensure your pull request is made to the `test` branch, not `main`.

*Thank you for contributing to Talk-Trove! We look forward to reviewing your PR and getting it merged!*

2024-10-10 06:08 UTC, jvkousthub commented
@kartikayasija Please review and let me know if any changes required

2024-10-14 08:22 UTC, Sibam-Paul requested changes

2024-10-14 08:22 UTC, Sibam-Paul commented on frontend/src/components/Authentication/Signup.js
> +  const getPasswordStrengthColor=()=>{
U have added color make it like the user can't signup without giving strong password and give a hidden response when the user enters low strength password
like 
![image](https://github.com/user-attachments/assets/15a9725f-5f38-47ff-b812-7b1cecfe2a06)

like here

2024-10-22 13:42 UTC, jvkousthub commented
@Sibam-Paul please check

2024-10-22 15:38 UTC, Sibam-Paul commented
Add a video plz

2024-11-12 10:44 UTC, closed without merging